name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Adicionado aqui também

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          
      - name: Install build
        run: pip install build
        
      - name: Build package
        run: python -m build
        
      - name: List artifacts
        run: ls -la dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
    permissions:
      id-token: write  # Crucial para trusted publishing
      
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
          
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
