name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: pip install build
    
    - name: Build package
      run: python -m build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package
        path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment: pypi  # ← DEVE corresponder ao configurado no PyPI
    permissions:
      id-token: write  # ← OBRIGATÓRIO para OIDC
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: python-package
        path: dist/
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # NÃO use 'with:' para credentials - OIDC automático
